# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c08e838b5e2febbef94b7b15f9765570c0ad9c580ec415c3b38a2f06a8512293c5fdf26a974174d9a756cc18f7862be7c76990672b5fb35f9fcf7b8e57b16b

test:
  secret_key_base: 88664b583be7124cfee71c99999308e9577a5aa0379c233a7cd6297a9651292f759f0b4a2064ed364066dbe1988d0a41c2f24e28e10acbd42fe8848220073e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
